repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.3
    hooks:
      - id: check-github-workflows
      - id: check-renovate

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: python -m ruff check
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format --check
        entry: python -m ruff format --check
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: python -m mypy shared/python tests
        language: system
        pass_filenames: false
